import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const D=window.SV_DATA, UI=window.SV_UI, $=s=>document.querySelector(s);
const clamp=THREE.MathUtils.clamp, rnd=(a,b)=>a+Math.random()*(b-a), lerp=(a,b,t)=>a+(b-a)*t;
const canvas=$('#scene'), cinematic=$('#cinematic'), cinematicLines=[...document.querySelectorAll('.cine-line')], isMobile=matchMedia('(pointer:coarse)').matches||innerWidth<760;
const S={scene:null,camera:null,renderer:null,clock:new THREE.Clock(),player:{x:0,z:0,y:0,yaw:0,vy:0,ground:true},
 yaw:0,pitch:.33,dist:isMobile?12:15,keys:Object.create(null),drag:false,px:0,py:0,locked:false,started:false,
 nearby:null,visited:{},secrets:{},done:{},productCount:0,cycle:true,time:.38,timeSpeed:1/600,quality:'high',waypoint:null,skipRequested:false,
 colliders:[],targets:[],districts:[],landmarks:[],animated:[],avatar:null,frame:0,fpsAt:performance.now(),
 mapAt:0, worldBuilt:false, interactEnabled:false, lastMove:0, touchX:0,touchY:0};
const C={
 dark:new THREE.MeshStandardMaterial({color:0x20252d,metalness:.79,roughness:.38}), metal:new THREE.MeshStandardMaterial({color:0x92999f,metalness:.91,roughness:.34}),
 stone:new THREE.MeshStandardMaterial({color:0x62666a,metalness:.12,roughness:.84}), ground:new THREE.MeshStandardMaterial({color:0x171a20,metalness:.08,roughness:.93}),
 asphalt:new THREE.MeshStandardMaterial({color:0x11141a,metalness:.05,roughness:.95}), glass:new THREE.MeshPhysicalMaterial({color:0x8299ad,metalness:.26,roughness:.2,transparent:true,opacity:.36,transmission:.15,clearcoat:.8}),
 copper:new THREE.MeshStandardMaterial({color:0x9e6540,metalness:.72,roughness:.34}), trim:new THREE.MeshStandardMaterial({color:0xc6c8c4,metalness:.78,roughness:.3})};
const ACC={}; D.DISTRICTS.forEach(d=>ACC[d.key]=new THREE.MeshStandardMaterial({color:d.color,metalness:.48,roughness:.35,emissive:new THREE.Color(d.color).multiplyScalar(.065)}));
const BOX_CACHE=new Map();
function mesh(parent,x,y,z,w,h,d,material,opts={}){const key=[w,h,d].join(':');let geo=BOX_CACHE.get(key);if(!geo){geo=new THREE.BoxGeometry(w,h,d);BOX_CACHE.set(key,geo);}const m=new THREE.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=opts.cast===true;m.receiveShadow=opts.receive===true;if(opts.userData)Object.assign(m.userData,opts.userData);parent.add(m);return m;}
function cyl(parent,x,y,z,rt,rb,h,material,seg=10){const m=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,seg),material);m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
function textSprite(text,x,y,z,sx,sy,opts={}){const c=document.createElement('canvas');c.width=512;c.height=128;const g=c.getContext('2d');if(opts.bg){g.fillStyle=opts.bg;g.fillRect(0,0,512,128);}g.textAlign='center';g.textBaseline='middle';g.font=`${opts.weight||700} ${opts.size||70}px Arial`;g.fillStyle=opts.color||'#f4f3ef';g.shadowColor=opts.glow||'rgba(255,176,102,.3)';g.shadowBlur=opts.blur||8;g.fillText(text,256,64,496);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.generateMipmaps=false;t.minFilter=THREE.LinearFilter;const m=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthWrite:false}));m.position.set(x,y,z);m.scale.set(sx,sy,1);return m;}
function target(obj,r,label,kind,payload){obj.userData.interact={r,label,kind,payload};S.targets.push(obj);return obj;}
function collider(x,z,hx,hz){S.colliders.push({x,z,hx,hz});}
function addInfo(text,x,z,color=0xf1f2ed,w=18){const g=new THREE.Group();g.position.set(x,0,z);S.scene.add(g);mesh(g,0,1.35,0,w,2.7,.18,C.dark);mesh(g,0,2.68,.13,w,.08,.08,C.trim,{cast:false});g.add(textSprite(text,0,1.4,.18,w-.4,1.45,{size:53,color:`#${color.toString(16).padStart(6,'0')}`}));return g;}
function boot(progress,label){try{const msg=document.querySelector('#bootMsg');if(msg&&label!=null)msg.textContent=label;const bar=document.querySelector('#bootBar');if(bar&&progress!=null)bar.style.width=progress+'%';}catch(_){}}
function fallback(err){try{console.error('[SOEMITROVERSE] 3D init failed',err);}catch(_){}
 try{if(typeof window.SV_renderFallback==='function'){const stage=document.querySelector('#stage');if(stage)stage.hidden=true;const fb=document.querySelector('#fallback');if(fb)fb.hidden=false;const b=document.querySelector('#boot');if(b)b.classList.add('gone');window.SV_renderFallback();}}catch(_){}}
function createGround(){const base=mesh(S.scene,0,-.55,0,860,1,860,C.ground,{cast:false});mesh(S.scene,0,-.05,0,22,.12,690,C.asphalt,{cast:false});mesh(S.scene,0,-.04,0,690,.12,22,C.asphalt,{cast:false});
 new THREE.Mesh(new THREE.CircleGeometry(62,96),new THREE.MeshStandardMaterial({color:0x111419,roughness:.92}));
 const ringMat=C.metal;[49,54,59].forEach(r=>{const m=new THREE.Mesh(new THREE.RingGeometry(r,r+.13,112),ringMat);m.rotation.x=-Math.PI/2;m.position.y=-.31;S.scene.add(m);});
 for(const d of D.DISTRICTS){const midx=d.x*.5,midz=d.z*.5;if(Math.abs(d.x)>Math.abs(d.z))mesh(S.scene,midx,-.42,d.z,Math.abs(d.x)+9,.14,10,C.asphalt,{cast:false});else mesh(S.scene,d.x,-.42,midz,10,.14,Math.abs(d.z)+9,C.asphalt,{cast:false});}
 // distant urban silhouette: low draw cost, readable city scale.
 for(let i=0;i<75;i++){const a=rnd(0,Math.PI*2),r=rnd(300,405),w=rnd(9,24),h=rnd(25,76);mesh(S.scene,Math.cos(a)*r,h/2,Math.sin(a)*r,w,h,w,i%3?C.dark:C.stone,{cast:false,receive:false});}
 // restrained landscaped pockets.
 for(const [cx,cz] of [[0,-77],[0,77],[-77,0],[77,0]])for(let i=0;i<6;i++){const x=cx+rnd(-9,9),z=cz+rnd(-9,9);mesh(S.scene,x,.3,z,2.3,.6,2.3,C.dark,{cast:false});cyl(S.scene,x,1.3,z,.17,.24,1.9,C.copper,6);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(1.15,1),new THREE.MeshStandardMaterial({color:0x65705c,roughness:.92}));crown.position.set(x,2.4,z);S.scene.add(crown);}
}
function buildTower(){const g=new THREE.Group();g.name='SOEMITRO TOWER';S.scene.add(g);
 mesh(g,0,3.2,0,49,6,39,C.dark);mesh(g,0,6.5,0,45,.7,35,C.trim);mesh(g,0,7,0,39,.5,30,C.dark);
 mesh(g,0,32,0,24,49,21,C.stone);mesh(g,0,58,0,18,.55,16,C.trim);mesh(g,0,60,0,15,4,13,C.dark);mesh(g,0,62.3,0,12,.6,11,C.trim);mesh(g,0,67,0,11,8,9,C.dark);cyl(g,0,75,0,.6,.7,8,C.trim,8);cyl(g,0,82,0,.16,.27,6,C.copper,8);
 const fins=new THREE.InstancedMesh(new THREE.BoxGeometry(.35,48,.35),C.metal,20),dummy=new THREE.Object3D();for(let i=0;i<20;i++){const a=i/20*Math.PI*2;dummy.position.set(Math.sin(a)*12,32,Math.cos(a)*10.7);dummy.rotation.y=a;dummy.updateMatrix();fins.setMatrixAt(i,dummy.matrix);}g.add(fins);
 for(let y=15;y<57;y+=7){mesh(g,0,y,-10.7,22,3.5,.08,C.glass,{cast:false});mesh(g,0,y+1.85,-10.77,23,.14,.1,C.metal,{cast:false});}
 mesh(g,0,13,11,30,7,.45,C.dark);g.add(textSprite('ADHITHYA',0,14.3,10.73,23,2.5,{size:92}));g.add(textSprite('PRANANDRA',0,11.9,10.73,20,2,{size:70}));g.add(textSprite('SOEMITRO',0,9.75,10.73,18,1.7,{size:65,color:'#ffb066'}));g.add(textSprite('FOUNDER · PRODUCT BUILDER · TECHNOLOGY LEADER · AI TRAINER',0,6,19.5,31,1.7,{size:29,color:'#d8e1eb'}));
 mesh(g,0,3.4,19.5,10,6.8,.7,C.dark);mesh(g,0,3.4,19.9,8,6,.08,C.glass,{cast:false});
 for(const r of [31,36,43]){const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.1,5,128),C.metal);ring.rotation.x=Math.PI/2;ring.position.y=.12;g.add(ring);}
 const light=new THREE.PointLight(0xffb066,4,52);light.position.set(0,13,-23);g.add(light);
 collider(0,0,24,20);target(g,30,'ENTER TOWER','view','about');S.landmarks.push({key:'tower',name:'SOEMITRO TOWER',x:0,z:0});return g;}
function building(key,name,x,z,w,d,h,mode='terrace'){const g=new THREE.Group();g.position.set(x,0,z);g.name=name;S.scene.add(g);const a=ACC[key]||C.trim;const front=z<0?1:-1;
 mesh(g,0,.55,0,w+3,1.1,d+3,C.dark);mesh(g,0,1.3,0,w,1,d,C.metal);mesh(g,0,2,0,w-1,1.2,d-1,C.stone);
 if(mode==='glass'){mesh(g,0,h*.5,0,w,h*.76,d,C.glass,{cast:false});for(let xx=-w/2+1;xx<w/2;xx+=2.7)mesh(g,xx,h*.5,-d/2-.08,.13,h*.76,.14,C.metal,{cast:false});}
 else{mesh(g,0,h*.48,0,w,h*.7,d,C.stone);mesh(g,0,h*.86,0,w*.82,h*.2,d*.82,C.dark);mesh(g,0,h*.98,0,w*.62,.55,d*.62,a);}
 for(let y=4;y<h*.75;y+=4.7)mesh(g,0,y,front*(d/2+.07),w*.8,.15,.14,a,{cast:false});
 mesh(g,0,2,front*(d/2+.15),Math.min(4,w*.24),3.6,.24,C.dark);mesh(g,0,2,front*(d/2+.29),Math.min(3,w*.2),3,.06,C.glass,{cast:false});g.add(textSprite(name,0,h+2.2,front*(d/2+.22),Math.min(w+4,30),2.5,{size:72}));
 collider(x,z,w/2+1.3,d/2+1.3);target(g,Math.max(w,d)*.65+9,name,'district',key);S.landmarks.push({key,name,x,z});return g;}
function buildHQ(){const d=D.DISTRICTS.find(x=>x.key==='founder'),g=building('founder','FOUNDER HQ',d.x,d.z,39,31,31);g.add(textSprite('PT. AGRA KARYA DIGITAL',0,34,15.9,28,2,{size:67,color:'#ffcf9d'}));g.add(textSprite('VERYCOOLAPPS',0,31.5,15.9,20,1.7,{size:67}));mesh(g,0,10,16.2,16,17,.3,C.glass,{cast:false});mesh(g,0,4.2,18.2,17,.4,6,C.dark);
 const products=[...D.IOS_APPS,...D.IOS_GAMES,...D.MAC_GAMES,...D.ROBLOX_GAMES.map(name=>({name,cat:'Roblox Experience'})),...D.WEB_APPS];const r=31;
 products.forEach((p,i)=>{const a=i/products.length*Math.PI*2,x=d.x+Math.cos(a)*r,z=d.z+Math.sin(a)*r,k=new THREE.Group();k.position.set(x,0,z);S.scene.add(k);cyl(k,0,.35,0,1.3,1.5,.7,C.dark,8);cyl(k,0,.78,0,1.05,1.25,.18,C.metal,8);
 if(i%4===0){mesh(k,0,1.8,0,1.1,1.45,.3,C.dark);mesh(k,0,1.82,.17,.86,1.16,.04,ACC.product,{cast:false});}else if(i%4===1)cyl(k,0,1.7,0,.67,.67,1.3,ACC.product,8);else if(i%4===2){const o=new THREE.Mesh(new THREE.OctahedronGeometry(.78),C.trim);o.position.y=1.8;k.add(o);}else mesh(k,0,1.75,0,1.4,1,.65,C.dark);
 k.add(textSprite(p.name,0,3.2,0,4.8,.85,{size:42,color:'#e9edf2',bg:'rgba(8,10,14,.8)'}));const data={...p,type:p.cat?'app':'game'};target(k,5,'VIEW PRODUCT','product',data);collider(x,z,1.7,1.7);
 });addInfo('50+ COMMERCIAL PRODUCTS',d.x,d.z+42,0xffb066,24);return g;}
function buildProduct(){const d=D.DISTRICTS.find(x=>x.key==='product');const g=building('product','PRODUCT DISTRICT',d.x,d.z,32,29,24,'glass');g.add(textSprite('PRODUCT LIFECYCLE',0,27,-14.8,22,1.8,{size:58,color:'#d9e8fa'}));
 D.LIFECYCLE.forEach((p,i)=>{const a=-Math.PI/2+i/6*Math.PI*2,r=43,x=d.x+Math.cos(a)*r,z=d.z+Math.sin(a)*r,s=new THREE.Group();s.position.set(x,0,z);S.scene.add(s);cyl(s,0,.24,0,3.8,4.2,.45,C.dark,8);cyl(s,0,.52,0,3.1,3.5,.15,C.metal,8);if(i===0){const o=new THREE.Mesh(new THREE.OctahedronGeometry(1.5),ACC.product);o.position.y=2.2;s.add(o);}else if(i===1)mesh(s,0,2.1,0,2.5,3,2.5,C.glass);else if(i===2)mesh(s,0,2.1,0,2.8,3,2,C.dark);else if(i===3)mesh(s,0,2,0,3,3,.4,C.metal);else if(i===4){const q=new THREE.Mesh(new THREE.TorusGeometry(1.3,.18,8,30),ACC.product);q.position.y=2.2;s.add(q);}else cyl(s,0,2,0,1,.7,3,C.metal,8);s.add(textSprite(p.key,0,4.3,0,6,1.2,{size:66}));target(s,8,'EXPLORE '+p.key,'lifecycle',p);collider(x,z,3.8,3.8);});return g;}
function buildGames(){const d=D.DISTRICTS.find(x=>x.key==='game'),g=building('game','GAME STUDIO',d.x,d.z,33,26,22);g.add(textSprite('GAME STUDIO',0,25,-13.5,19,2,{size:70,color:'#c8f5dc'}));
 D.MAC_GAMES.forEach((p,i)=>{const x=d.x+(i-1)*24,z=d.z-37,q=new THREE.Group();q.position.set(x,0,z);S.scene.add(q);mesh(q,-5.4,6,0,1.4,12,1.6,C.dark);mesh(q,5.4,6,0,1.4,12,1.6,C.dark);mesh(q,0,11.6,0,12.2,1.4,1.6,ACC.game);mesh(q,0,5.8,-.2,9.5,9.8,.06,new THREE.MeshBasicMaterial({color:0x658a72,transparent:true,opacity:.12,side:THREE.DoubleSide}),{cast:false});q.add(textSprite(p.name.toUpperCase(),0,13.3,-.7,15,1.8,{size:52}));q.add(textSprite(p.genre+' · '+p.engine,0,1.2,-.7,13,1,{size:28,color:'#bfd0c1'}));target(q,9,'ENTER PROJECT PORTAL','project',p);S.landmarks.push({key:'portal-'+i,name:p.name,x,z});});
 D.ROBLOX_GAMES.forEach((name,i)=>{const row=Math.floor(i/5),col=i%5,x=d.x-35+col*17,z=d.z+31+row*15,p=new THREE.Group();p.position.set(x,0,z);S.scene.add(p);mesh(p,0,.5,0,10,1,7,C.dark);mesh(p,0,2.3,0,8.5,2.6,5.8,i%2?C.stone:C.metal);mesh(p,0,3.7,0,9,.14,6.2,ACC.game,{cast:false});p.add(textSprite(name.toUpperCase(),0,4.7,-2.7,8.2,1.1,{size:48,bg:'rgba(8,10,12,.82)'}));target(p,7.5,'VIEW ROBLOX PROJECT','roblox',name);collider(x,z,5,3.7);});addInfo('ROBLOX · INTERACTIVE MEDIA · EXPERIMENTAL GAMES',d.x,d.z+96,0x9affd0,33);return g;}
function buildAcademy(){const d=D.DISTRICTS.find(x=>x.key==='academy'),g=building('academy','SOEMITRO ACADEMY',d.x,d.z,36,31,27);g.add(textSprite('SOEMITRO ACADEMY',0,30,-15.7,25,2.2,{size:70,color:'#ffe3b4'}));mesh(g,0,8,-16.3,22,13,.3,C.glass,{cast:false});mesh(g,0,2,30,20,4,.7,C.dark);g.add(textSprite('TECHNOLOGY IS ONLY POWERFUL WHEN PEOPLE KNOW HOW TO USE IT.',0,4.5,29.55,23,1.6,{size:37,color:'#ffe6c2'}));const modules=[['AI TRAINING','Practical AI training and workflow adoption.'],['AI LITERACY','Understanding capability, limits and responsible use.'],['PROMPTING','Clear instructions; structured results; repeatable workflows.'],['WORKSHOPS','Hands-on sessions and guided practice.'],['KNOWLEDGE SHARING','Technology translated into usable knowledge.']];modules.forEach((m,i)=>{const x=d.x-28+i*14,z=d.z+44,p=new THREE.Group();p.position.set(x,0,z);S.scene.add(p);mesh(p,0,1.4,0,8.4,2.8,6.4,C.dark);mesh(p,0,3,0,7.7,.14,5.8,ACC.academy,{cast:false});p.add(textSprite(m[0],0,4.1,-3.1,8,1.1,{size:48}));target(p,7,'EXPLORE '+m[0],'academy',{name:m[0],description:m[1]});collider(x,z,4.4,3.4);});D.PROMPTERS.forEach((p,i)=>{const a=i/D.PROMPTERS.length*Math.PI*2,r=63,x=d.x+Math.cos(a)*r,z=d.z+Math.sin(a)*r,q=new THREE.Group();q.position.set(x,0,z);S.scene.add(q);cyl(q,0,.3,0,.9,1.1,.6,C.dark,6);mesh(q,0,1.3,0,1.25,1.4,.5,C.metal);mesh(q,0,1.3,.28,.9,1,.05,ACC.academy,{cast:false});q.add(textSprite(p.name,0,2.5,.1,4.5,.8,{size:39,bg:'rgba(8,10,12,.82)'}));target(q,5,'OPEN PROMPT TOOL','prompter',p);});return g;}

function buildStreetLights(){const pts=[];for(const d of D.DISTRICTS)for(let i=0;i<8;i++){const a=i/8*Math.PI*2;pts.push([d.x+Math.cos(a)*40,d.z+Math.sin(a)*40]);}const inst=new THREE.InstancedMesh(new THREE.CylinderGeometry(.11,.16,5.6,6),C.dark,pts.length),o=new THREE.Object3D();pts.forEach((p,i)=>{o.position.set(p[0],2.8,p[1]);o.updateMatrix();inst.setMatrixAt(i,o.matrix);});S.scene.add(inst);pts.filter((_,i)=>i%5===0).forEach(([x,z])=>{const l=new THREE.PointLight(0xffc88a,.35,17,2);l.position.set(x,5.2,z);S.scene.add(l);S.animated.push({type:'light',light:l,base:.35,phase:rnd(0,8)});});}
async function buildWorld(){
boot(16,'mapping city districts…');createGround();boot(28,'constructing Soemitro Tower…');buildTower();buildStreetLights();boot(42,'building Founder HQ and product gallery…');buildHQ();buildProduct();boot(58,'opening the Game District…');buildGames();boot(70,'building Soemitro Academy…');buildAcademy();boot(80,'assembling Technology Center and Archive…');let we=null;try{we=await import('./world-extras.js');}catch(e){console.warn('world-extras unavailable',e);}if(we&&we.buildAdditionalWorld)we.buildAdditionalWorld(S,D,{building,mesh,cyl,target,collider,textSprite,addInfo,C,ACC});boot(88,'shaping Future District and hidden rooms…');
 const player=new THREE.Group();player.name='Playable avatar';S.scene.add(player);const rig=new THREE.Group();player.add(rig);const suit=new THREE.MeshStandardMaterial({color:0x202832,roughness:.55,metalness:.2}),coat=new THREE.MeshStandardMaterial({color:0x11171e,roughness:.62,metalness:.18}),skin=new THREE.MeshStandardMaterial({color:0xb88968,roughness:.74}),hair=new THREE.MeshStandardMaterial({color:0x20201e,roughness:.9}),accent=new THREE.MeshStandardMaterial({color:0x9d704c,roughness:.32,metalness:.67}),shoe=new THREE.MeshStandardMaterial({color:0x090c10,roughness:.48});const head=new THREE.Group();head.position.y=1.53;rig.add(head);mesh(rig,0,1.1,0,.65,.84,.37,coat);mesh(rig,0,1.49,0,.61,.12,.38,suit);const lap=mesh(rig,-.11,1.31,.2,.12,.34,.03,accent);lap.rotation.z=-.22;const lap2=mesh(rig,.11,1.31,.2,.12,.34,.03,accent);lap2.rotation.z=.22;mesh(rig,0,1.59,0,.18,.18,.17,skin);mesh(head,0,.21,0,.39,.45,.33,skin);mesh(head,0,.43,-.01,.41,.15,.35,hair);const arms=[],legs=[];for(const side of [-1,1]){const a=new THREE.Group();a.position.set(side*.4,1.36,0);rig.add(a);mesh(a,0,-.24,0,.22,.5,.22,suit);mesh(a,0,-.51,.01,.2,.16,.2,skin);arms.push(a);const l=new THREE.Group();l.position.set(side*.16,.73,0);rig.add(l);mesh(l,0,-.23,0,.26,.53,.3,suit);mesh(l,0,-.52,.08,.31,.15,.44,shoe);legs.push(l);}mesh(rig,.33,1.58,-.05,.075,.15,.09,accent);const disk=new THREE.Mesh(new THREE.CircleGeometry(.44,20),new THREE.MeshBasicMaterial({color:0x08090c,transparent:true,opacity:.3,depthWrite:false}));disk.rotation.x=-Math.PI/2;disk.position.y=.02;player.add(disk);S.avatar={root:player,rig,head,arms,legs};
 buildFuturePlaceholder();
 boot(94,'optimizing lighting and camera…');}
function buildFuturePlaceholder(){/* future, archive and command architecture are created by world-extras module; secrets in this district remain discoverable through its portal landmarks. */}

function makeRenderer(){try{const gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'})||canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!gl)throw new Error('WebGL context unavailable');const renderer=new THREE.WebGLRenderer({canvas,context:gl,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,isMobile?1.35:1.8));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=!isMobile;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.info.autoReset=true;S.renderer=renderer;return renderer;}catch(e){throw new Error('WebGL renderer creation failed: '+e.message);}}
function makeLighting(){S.scene.background=new THREE.Color(0x777e85);S.scene.fog=new THREE.FogExp2(0x777e85,.0018);S.hemi=new THREE.HemisphereLight(0xdce3ed,0x343842,1.35);S.scene.add(S.hemi);S.sun=new THREE.DirectionalLight(0xffeed9,3.0);S.sun.position.set(-180,240,-120);S.sun.castShadow=!isMobile;S.sun.shadow.mapSize.set(1024,1024);S.sun.shadow.camera.near=.5;S.sun.shadow.camera.far=480;S.sun.shadow.camera.left=-270;S.sun.shadow.camera.right=270;S.sun.shadow.camera.top=270;S.sun.shadow.camera.bottom=-270;S.sun.shadow.bias=-.00045;S.scene.add(S.sun);const fill=new THREE.DirectionalLight(0x8da8cc,.55);fill.position.set(180,100,170);S.scene.add(fill);const ambient=new THREE.AmbientLight(0x8993a5,.34);S.scene.add(ambient);}
function onTime(name){const map={sunset:.21,night:.79,sunrise:.04};S.time=map[name]??.21;S.cycle=false;updateTime(0);}
function updateTime(dt){if(!isFinite(S.time))S.time=.21;if(S.cycle&&isFinite(S.timeSpeed))S.time=(S.time+dt*S.timeSpeed)%1;const t=isFinite(S.time)?S.time:.21;const sunY=Math.sin((t-.25)*Math.PI*2);const daylight=clamp((sunY+.17)*1.3,0,1);const sunset=Math.max(0,1-Math.abs(t-.22)*10);const night=1-daylight;const sky=new THREE.Color().setRGB(lerp(.025,.53,daylight)+sunset*.18,lerp(.035,.57,daylight)+sunset*.08,lerp(.07,.62,daylight));S.scene.background.copy(sky);S.scene.fog.color.copy(sky);S.scene.fog.density=lerp(.0024,.0016,daylight);S.sun.position.set(Math.cos(t*Math.PI*2)*260,Math.max(18,sunY*300),Math.sin(t*Math.PI*2)*260);S.sun.intensity=lerp(.34,3.2,daylight);S.hemi.intensity=lerp(.55,1.45,daylight);S.renderer.toneMappingExposure=lerp(.82,1.08,daylight);for(const d of D.DISTRICTS)ACC[d.key].emissiveIntensity=lerp(.22,.035,daylight);const slider=$('#timeSlider');if(slider&&document.activeElement!==slider)slider.value=Math.round(t*100);}
function setQuality(q){S.quality=q;const settings={ultra:{dpr:2,shadow:!isMobile,map:2048},high:{dpr:1.6,shadow:!isMobile,map:1024},medium:{dpr:1.25,shadow:false,map:512},low:{dpr:1,shadow:false,map:256}}[q]||{dpr:1.3,shadow:false,map:512};S.renderer.setPixelRatio(Math.min(devicePixelRatio,isMobile?Math.min(settings.dpr,1.35):settings.dpr));S.renderer.shadowMap.enabled=settings.shadow;S.sun.castShadow=settings.shadow;S.sun.shadow.mapSize.set(settings.map,settings.map);S.renderer.setSize(innerWidth,innerHeight);}

function initUI(){UI.init({onPanelOpen(open){S.paused=open;},onTime,onTimeSlider(v){S.time=v/100;S.cycle=false;updateTime(0);},onCycle(v){S.cycle=v;},onQuality:setQuality,onWaypoint(key){const d=D.DISTRICTS.find(q=>q.key===key);if(d){S.waypoint={x:d.x,z:d.z,name:d.name};S.paused=false;UI.toast('WAYPOINT SET · '+d.name,true);$('#mapPanel').classList.remove('open');}},});UI.initMinimap(D.DISTRICTS,[]);}

function buildMobileControls(){if(!isMobile)return;const joy=document.createElement('div');joy.className='joystick';joy.innerHTML='<div class="joystick-knob"></div>';document.body.appendChild(joy);const knob=joy.firstElementChild;const actions=document.createElement('div');actions.className='joy-actions';actions.innerHTML='<button data-action="jump">JUMP</button><button data-action="interact">USE</button>';document.body.appendChild(actions);joy.classList.add('on');actions.classList.add('on');let active=false,cx=0,cy=0;joy.addEventListener('pointerdown',e=>{active=true;joy.setPointerCapture(e.pointerId);const r=joy.getBoundingClientRect();cx=r.left+r.width/2;cy=r.top+r.height/2;move(e);});joy.addEventListener('pointermove',e=>{if(active)move(e);});function move(e){const dx=e.clientX-cx,dy=e.clientY-cy,max=40,len=Math.hypot(dx,dy)||1,k=Math.min(max,len);knob.style.transform=`translate(${dx/len*k}px,${dy/len*k}px)`;S.touchX=dx/len*(k/max);S.touchY=dy/len*(k/max);}function end(){active=false;S.touchX=0;S.touchY=0;knob.style.transform='';}joy.addEventListener('pointerup',end);joy.addEventListener('pointercancel',end);actions.addEventListener('pointerdown',e=>{const a=e.target.closest('button')?.dataset.action;if(a==='jump'){S.player.vy=7.5;S.player.ground=false;}if(a==='interact')doInteract();});}
function initInput(){window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();S.keys[k]=true;if(k===' '){e.preventDefault();if(S.started&&S.player.ground){S.player.vy=7.2;S.player.ground=false;}}if(k==='e')doInteract();});window.addEventListener('keyup',e=>S.keys[e.key.toLowerCase()]=false);
 canvas.addEventListener('pointerdown',e=>{if(isMobile)return;if(e.button!==0)return;S.drag=true;S.px=e.clientX;S.py=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!S.drag||S.locked)return;const dx=e.clientX-S.px,dy=e.clientY-S.py;S.yaw-=dx*.004;S.pitch=clamp(S.pitch-dy*.003,-.08,.82);S.px=e.clientX;S.py=e.clientY;});canvas.addEventListener('pointerup',()=>S.drag=false);canvas.addEventListener('pointercancel',()=>S.drag=false);
 canvas.addEventListener('click',()=>{if(!isMobile&&S.started&&!S.locked&&canvas.requestPointerLock){canvas.requestPointerLock().catch(()=>{});}});document.addEventListener('pointerlockchange',()=>{S.locked=document.pointerLockElement===canvas;});document.addEventListener('mousemove',e=>{if(S.locked){S.yaw-=e.movementX*.0022;S.pitch=clamp(S.pitch-e.movementY*.0018,-.08,.82);}});
 canvas.addEventListener('touchstart',e=>{if(e.touches.length===1){S.px=e.touches[0].clientX;S.py=e.touches[0].clientY;}},{passive:true});canvas.addEventListener('touchmove',e=>{if(e.touches.length===1){const t=e.touches[0],dx=t.clientX-S.px,dy=t.clientY-S.py;S.yaw-=dx*.004;S.pitch=clamp(S.pitch-dy*.003,-.06,.78);S.px=t.clientX;S.py=t.clientY;}},{passive:true});
 $('#enterBtn').addEventListener('click',enterWorld);$('#cineSkip').addEventListener('click',requestEnter);$('#bootSkip').addEventListener('click',requestEnter);window.addEventListener('keydown',e=>{if(e.key==='Enter'&&!S.started){if(!$('#enterBtn').disabled)enterWorld();else requestEnter();}});window.addEventListener('resize',()=>{if(!S.camera)return;S.camera.aspect=innerWidth/innerHeight;S.camera.updateProjectionMatrix();S.renderer.setSize(innerWidth,innerHeight);setQuality(S.quality);});$('#cpClose').addEventListener('click',()=>$('#controlsPrev').classList.remove('show'));}

function showCareer(c){return '<div class="h-title">'+c.role+'</div><div class="h-sub">'+c.period+' · '+c.org+'</div><p class="h-desc">'+c.summary+'</p><div class="h-sec-t">PROJECTS / CONTRIBUTIONS</div><p class="h-desc">'+c.have+'</p><div class="h-sec-t">TECHNOLOGY</div><div class="h-chips">'+c.tech.map(x=>'<span class="h-chip">'+x+'</span>').join('')+'</div><div class="h-sec-t">IMPACT</div><p class="h-desc">'+c.impact+'</p>';}
function openProject(p){const title=p.name||'Project';const platform=p.cat==='Roblox Experience'?'Roblox':p.genre?'macOS':p.kind?'Web':p.type==='app'?'iOS':p.type==='game'?'iOS Game':p.cat||'Web';const tech=p.engine||p.technology||'Not specified in verified source';const year=p.year||'Not listed in verified source';const link=p.url||p.link||'';const body='<div class="h-title">'+title+'</div><div class="h-sub">VERIFIED PROJECT</div><p class="h-desc">'+(p.description||p.genre||p.cat||p.kind||'Project listed in the official portfolio.')+'</p><div class="h-grid"><div class="h-cell"><dt>PROJECT</dt><dd>'+title+'</dd></div><div class="h-cell"><dt>ROLE</dt><dd>Creator &amp; developer</dd></div><div class="h-cell"><dt>PLATFORM</dt><dd>'+platform+'</dd></div><div class="h-cell"><dt>TECHNOLOGY</dt><dd>'+tech+'</dd></div><div class="h-cell"><dt>YEAR</dt><dd>'+year+'</dd></div></div>'+(link?'<div class="h-cta"><a class="sv-btn primary" href="'+link+'" target="_blank" rel="noopener">OPEN PROJECT ↗</a></div>':'<div class="h-note">No public project link was listed in the verified source.</div>');UI.openHolo('PROJECT',body);}
function doInteract(){if(!S.nearby)return;const item=S.nearby,meta=item.userData.interact||{};const kind=meta.kind,p=meta.payload;S.nearby=null;UI.setInteract(null);if(kind==='product'||kind==='project'||kind==='prompter'||kind==='roblox'){if(kind==='prompter')openProject({...p,cat:'AI Prompt Tool',type:'web'});else if(kind==='roblox')openProject({name:p,cat:'Roblox Experience'});else openProject(p);S.productCount++;if(S.productCount>=3)completeQuest(1);return;}
 if(kind==='district'){const k=p||item.name.toLowerCase().replace(/\s/g,'');S.visited[k]=true;const q=D.DISTRICTS.find(d=>d.key===k);if(q)UI.setZone(q.name);else UI.setZone(item.name||'SOEMITROVERSE');if(k==='founder')completeQuest(0);if(k==='game')completeQuest(2);if(k==='academy')completeQuest(3);if(k==='command')completeQuest(5);if(k==='founder')UI.openView('about');else if(k==='command')UI.openView('contact');else UI.toast('ENTERED · '+(q?.name||item.name),true);return;}
 if(kind==='view'){UI.openView(p);if(p==='contact')completeQuest(5);return;}
 if(kind==='lifecycle'){UI.openHolo('PRODUCT LIFECYCLE','<div class="h-title">'+p.key+'</div><div class="h-sub">IDEA → PROTOTYPE → BUILD → LAUNCH → ITERATE → SCALE</div><p class="h-desc">'+p.desc+'</p>');return;}
 if(kind==='academy'){UI.openHolo('SOEMITRO ACADEMY','<div class="h-title">'+p.name+'</div><div class="h-sub">AI TRAINING · AI LITERACY · PROMPTING</div><p class="h-desc">'+p.description+'</p><p class="h-desc">The Academy represents practical AI training, education and knowledge sharing—technology translated for people to use.</p>');return;}
 if(kind==='tech'){UI.openHolo('TECHNOLOGY CENTER','<div class="h-title">'+p.name+' · SYSTEM PIPELINE</div><div class="h-sub">SOFTWARE · AI / LLM DEPLOYMENT · DIGITAL TRANSFORMATION</div><p class="h-desc">'+p.description+'</p><p class="h-desc">Architecture and delivery experience across product strategy, software, AI tooling and automation.</p>');return;}
 if(kind==='career'){UI.openHolo('THE ARCHIVE',showCareer(p));return;}
 if(kind==='skill'){UI.openHolo('SKILL CONSTELLATION','<div class="h-title">'+p.key+'</div><div class="h-sub">CORE COMPETENCY · '+p.code+'</div><p class="h-desc">'+p.detail+'</p><div class="h-sec-t">VERIFIED EVIDENCE</div><div class="h-chips">'+p.evidence.map(x=>'<span class="h-chip">'+x+'</span>').join('')+'</div>');return;}
 if(kind==='secret'){S.secrets[p.name]=true;UI.openHolo('CLASSIFIED · DISCOVERED','<div class="h-title">'+p.name+'</div><div class="h-sub">YOU FOUND SOMETHING MOST VISITORS NEVER SEE.</div><p class="h-desc">'+p.note+'</p>');completeQuest(4);return;}
 if(kind==='future'){UI.toast('CURRENTLY BUILDING THE NEXT THING.',true);return;}
}
function completeQuest(i){if(S.done[i])return;S.done[i]=true;const count=Object.keys(S.done).length;UI.setQuestProgress(count/D.QUESTS.length*100);UI.toast('QUEST COMPLETE · '+D.QUESTS[i].text,true);let next=D.QUESTS.findIndex((q,j)=>!S.done[j]);if(next>=0)UI.setQuest(next,D.QUESTS[next].text);else UI.setQuest(5,'WORLD EXPLORATION COMPLETE');}
function findNearest(){let best=null,bd=Infinity;const x=S.player.x,z=S.player.z;for(const o of S.targets){const m=o.userData.interact;if(!m)continue;const dx=o.position.x+x*0,z=o.position.z;const wx=o.getWorldPosition(new THREE.Vector3());const d=Math.hypot(wx.x-x,wx.z-z);if(d<m.r&&d<bd){best=o;bd=d;}}return best;}
function updatePlayer(dt,t){let ix=0,iz=0;if(S.keys.w||S.keys.arrowup)iz-=1;if(S.keys.s||S.keys.arrowdown)iz+=1;if(S.keys.a||S.keys.arrowleft)ix-=1;if(S.keys.d||S.keys.arrowright)ix+=1;if(isMobile){ix=-S.touchX;iz=S.touchY;}const len=Math.hypot(ix,iz);if(len>.01){ix/=len;iz/=len;}const forwardX=-Math.sin(S.yaw),forwardZ=-Math.cos(S.yaw),rightX=Math.cos(S.yaw),rightZ=-Math.sin(S.yaw);const speed=(S.keys.shift?16:10)*(isMobile?1:1);let nx=S.player.x+(rightX*ix+forwardX*iz)*speed*dt,nz=S.player.z+(rightZ*ix+forwardZ*iz)*speed*dt;for(const c of S.colliders){if(Math.abs(nx-c.x)<c.hx+.38&&Math.abs(S.player.z-c.z)<c.hz+.38)nx=S.player.x;if(Math.abs(nz-c.z)<c.hz+.38&&Math.abs(nx-c.x)<c.hx+.38)nz=S.player.z;}S.player.x=clamp(nx,-410,410);S.player.z=clamp(nz,-410,410);if(len>.01){S.player.yaw=Math.atan2(rightX*ix+forwardX*iz,rightZ*ix+forwardZ*iz);S.lastMove=t;}
 if(!S.player.ground){S.player.vy-=18*dt;S.player.y+=S.player.vy*dt;if(S.player.y<=0){S.player.y=0;S.player.vy=0;S.player.ground=true;}}const avatar=S.avatar;avatar.root.position.set(S.player.x,S.player.y,S.player.z);avatar.rig.rotation.y=S.player.yaw;const walk=len>.01?Math.sin(t*9)*.56:0;avatar.legs[0].rotation.x=walk;avatar.legs[1].rotation.x=-walk;avatar.arms[0].rotation.x=-walk*.52;avatar.arms[1].rotation.x=walk*.52;avatar.head.rotation.y=Math.sin(t*.75)*.025;}
function updateCamera(dt){const p=S.player;const target=new THREE.Vector3(p.x,p.y+1.15,p.z);const desired=new THREE.Vector3(p.x+Math.sin(S.yaw)*Math.cos(S.pitch)*S.dist,p.y+Math.sin(S.pitch)*S.dist+2.3,p.z+Math.cos(S.yaw)*Math.cos(S.pitch)*S.dist);S.camera.position.lerp(desired,1-Math.exp(-5*dt));S.camera.lookAt(target);}
function updateProximity(){let best=null,bd=Infinity;for(const o of S.targets){const m=o.userData.interact;if(!m)continue;const p=o.getWorldPosition(new THREE.Vector3()),dist=Math.hypot(p.x-S.player.x,p.z-S.player.z);if(dist<m.r&&dist<bd){best=o;bd=dist;}}if(best!==S.nearby){S.nearby=best;if(best){UI.setInteract(best.userData.interact.label,doInteract);}else UI.setInteract(null);}if(!S.visited.founder&&Math.hypot(S.player.x+170,S.player.z+170)<35)UI.setZone('FOUNDER HQ');else if(!S.visited.product&&Math.hypot(S.player.x-170,S.player.z+170)<35)UI.setZone('PRODUCT DISTRICT');else if(!S.visited.game&&Math.hypot(S.player.x+170,S.player.z-170)<35)UI.setZone('GAME DISTRICT');else if(!S.visited.academy&&Math.hypot(S.player.x-170,S.player.z-170)<35)UI.setZone('SOEMITRO ACADEMY');else if(Math.hypot(S.player.x,S.player.z)<55)UI.setZone('SOEMITRO PLAZA');}
function update(t,dt){if(S.paused){S.renderer.render(S.scene,S.camera);return;}updatePlayer(dt,t);updateCamera(dt);updateProximity();updateTime(dt);for(const a of S.animated){if(a.type==='light')a.light.intensity=a.base*(.75+.25*Math.sin(t*2+a.phase));}
 if(t-S.mapAt>.15){UI.drawMinimap(S.player.x,S.player.z,S.yaw,S.visited,S.waypoint);S.mapAt=t;}UI.updateCompass(THREE.MathUtils.radToDeg(S.yaw));S.frame++;const now=performance.now();if(now-S.fpsAt>850){const fps=Math.round(S.frame*1000/(now-S.fpsAt));S.frame=0;S.fpsAt=now;UI.updateFps(fps);if(fps<28&&S.quality!=='low'&&isMobile){setQuality('low');UI.toast('LOW POWER MODE · QUALITY REDUCED');}}S.renderer.render(S.scene,S.camera);}

function requestEnter(){if(S.started)return;if(S.ready){enterWorld();return;}S.skipRequested=true;window.__SV_SKIP_REQUESTED=true;const msg=$('#bootMsg');if(msg)msg.textContent='SKIP REQUESTED · ENTERING WHEN THE WORLD IS READY';}
function enterWorld(){if(S.started)return;S.started=true;S.paused=false;$('#cinematic').classList.add('gone');$('#stage').classList.add('active');$('#hud').hidden=false;$('#boot').classList.add('gone');S.player.x=0;S.player.z=30;S.yaw=0;S.pitch=.27;S.dist=isMobile?11.5:14;UI.setZone('SOEMITRO PLAZA');UI.setQuest(0,D.QUESTS[0].text);UI.setQuestProgress(0);$('#controlsPrev').classList.add('show');setTimeout(()=>$('#controlsPrev').classList.remove('show'),10000);buildMobileControls();}
window.__SV_ENTER_WORLD=enterWorld;
function playOpening(){const durations=[850,850,1050,1300];let i=0;function show(){if(i>=cinematicLines.length)return;const line=cinematicLines[i];if(i===2){$('#stage').classList.add('active');cinematic.classList.add('reveal');}line.classList.add('show');if(i===cinematicLines.length-1){$('#enterBtn').disabled=false;$('#cineBar').style.width='100%';return;}$('#cineBar').style.width=((i+1)/cinematicLines.length*100)+'%';setTimeout(()=>{line.classList.remove('current');i++;if(cinematicLines[i])cinematicLines[i].classList.add('current');show();},durations[Math.min(i,durations.length-1)]||900);}if(cinematicLines[0])cinematicLines[0].classList.add('current');setTimeout(show,250);}

async function init(){window.__SV_APP_STARTED=true;try{boot(5,'checking WebGL…');S.scene=new THREE.Scene();S.camera=new THREE.PerspectiveCamera(53,innerWidth/innerHeight,.1,1100);S.renderer=makeRenderer();makeLighting();S.camera.position.set(0,172,190);S.camera.lookAt(0,20,0);initUI();initInput();
 await buildWorld();S.worldBuilt=true;window.__SOEMITROVERSE_READY=true;$('#fallback').hidden=true;$('#stage').hidden=false;setQuality(isMobile?'medium':'high');updateTime(0);boot(100,'world ready');await new Promise(r=>setTimeout(r,220));$('#boot').classList.add('gone');playOpening();S.ready=true;if(S.skipRequested||window.__SV_SKIP_REQUESTED)enterWorld();
 const loop=()=>{requestAnimationFrame(loop);const dt=Math.min(S.clock.getDelta(),.045);update(S.clock.elapsedTime,dt);};loop();
 // Optional character asset prefetch is non-blocking; custom avatar stays the player character.
 if(!isMobile)import('three/addons/loaders/GLTFLoader.js').then(()=>{}).catch(()=>{});
 }catch(e){fallback(e);}}

init();

